spring.application.name=th

spring.datasource.url=jdbc:postgresql://localhost:5432/filesharingdb
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


file.upload-dir=uploads
